/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.cecar.dominoes.cliente.vista;

import edu.cecar.dominoes.cliente.logica.LogicaCliente;
import java.util.logging.Level;
import java.util.logging.Logger;


public class Listo extends javax.swing.JDialog {
    LogicaCliente logicaCliente;
    private boolean paraciclo=false;

    /**
     * Creates new form Listo
     */
    
    public void pararCiclo(){
        paraciclo=true;
    }
    public Listo(java.awt.Frame parent, boolean modal, LogicaCliente logicaCliente) {
        super(parent, modal);
        this.logicaCliente = logicaCliente;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        lbConectados = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                cargaFinal(evt);
            }
        });

        jLabel1.setText("¿Listo para la partida?");

        jButton1.setText("iniciar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        lbConectados.setText("Numero de conectados: 0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbConectados, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(jButton1)))
                .addContainerGap(119, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbConectados)
                .addGap(62, 62, 62)
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addComponent(jButton1)
                .addContainerGap(139, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        logicaCliente.estoyListo();
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cargaFinal(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_cargaFinal
        
        new Thread(()->{
            while (!paraciclo) {                
                try {
                    logicaCliente.getConectados(lbConectados);
                    
                    Thread.sleep(3000);
                } catch (InterruptedException ex) {
                    Logger.getLogger(Listo.class.getName()).log(Level.SEVERE, null, ex);
                }
                
            }
            
            
        }).start();
        
    }//GEN-LAST:event_cargaFinal

   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbConectados;
    // End of variables declaration//GEN-END:variables
}
